service:
  name: beam-service
  akkaPort:
    master:
      name: "akka-remote"
      type: None
      port : "2551"
    worker:
      name: "akka-remote"
      type: None
      port: 2552

secret:
  docker: dockerhub

deployment:
  image: ${beamImage}
  imageTag: ${beamImageTag}
  pullPolicy: Always
  pullSecret: dockerhub
  # Additional pod labels
  # ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels: {}

daemonset:
  image: "kmitin/s3fs"
  imageTag: "latest"
  bucket: ${bucketName}
  region: "us-west-2"
  pullPolicy: Always

volume:
  fuse:
    name: devfuse
    path: /dev/fuse
    host: /dev/fuse
  data:
    name: mount-data
    path: /s3data
    host: /dev/data-s3fs
  output:
    name: storage
    path: /opt/output

job:
  master:
    hostname: beam-master
  worker:
    hostname: beam-worker
    replicas: 3
  image: ${beamImage}
  imageTag: ${beamImageTag}
